<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Components\Pages\Weather.razor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorBiz.CasosDeUso\BlazorBiz.CasosDeUso.csproj" />
    <ProjectReference Include="..\BlazorBiz.Entidades\BlazorBiz.Entidades.csproj" />
    <ProjectReference Include="..\BlazorBiz.Plugins\BlazorBiz.PluginsTeste\BlazorBiz.PluginsTeste.csproj" />
  </ItemGroup>

</Project>
