// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpPontoWeb.Data;

#nullable disable

namespace SharpPontoWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
<<<<<<<< HEAD:SharpPontoWeb/Migrations/20250903103904_InitialCreate.Designer.cs
    [Migration("20250903103904_InitialCreate")]
========
    [Migration("20250901213738_InitialCreate")]
>>>>>>>> d44a908aba402fb54a4b9ae1e483d658bf7bba54:SharpPontoWeb/Migrations/20250901213738_InitialCreate.Designer.cs
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SharpPontoWeb.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("Almoco")
                        .HasColumnType("time(6)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Entrada")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("Manha")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("Retorno")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("Saida")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("Tarde")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("TotalDia")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
